#!/bin/bash

rand=$RANDOM
x=${rand:0:1}

echo "Lets play a game!"
echo "this computer will genete a random numeber between 0 and 9 "
echo "you need to guess which number !"
echo "enter the number that guessed!"
read n

while [[ $n -ne $x ]]
do
        echo "your guess is wrong!!"
        echo "enter number again!"
        read n

done

echo "you are right!!, the number you guessed is the same number generated by me!! that is $x"

